#ifndef CONST_SEEN
#define CONST_SEEN

#define WINDOW_NAME "Projekt"

#define ST_FPS 0

#define FLAG_ROTATE_CAMERA (unsigned int)0x1
#define FLAG_NOT_PAUSED (unsigned int)0x2
#define FLAG_WINDOW_ACTIVE (unsigned int)0x4
#define FLAG_FULLSCREEN (unsigned int)0x8
#define FLAG_FOG (unsigned int)0x10

#define TRACKING_NONE 0
#define TRACKING_CAMERA_XZ 1
#define TRACKING_CAMERA_XYZ 2
#define TRACKING_CAMERA_PARALELL 3
#define TRACKING_CAMERA_PLANE_XZ 4

#define TEXT_ALIGN_CENTER 0
#define TEXT_ALIGN_RIGHT 1
#define TEXT_ALIGN_LEFT 2

#define PROGRAM_PHONH 0
#define PROGRAM_TEXT 1

#define MODEL_CUBE 0
#define MODEL_SCREEN 1
#define MODEL_BOW 2
#define MODEL_CHERRY_TREE 3
#define MODEL_CHERRY_TREE_BLOSSOM 4
#define MODEL_ISLAND 5
#define MODEL_LANTERN 6
#define MODEL_TORII_GATE 7

#define TEXTURE_CUBE_CORONA 0
#define TEXTURE_CUBE_SPACE 1
#define TEXTURE_UV_BOW 2
#define TEXTURE_UV_CHERRY_TREE 3
#define TEXTURE_UV_CHERRY_TREE_BLOSSOM 4
#define TEXTURE_UV_GRASS 5
#define TEXTURE_UV_LANTERN 6
#define TEXTURE_UV_TORII_GATE 7

#define MATERIAL_COLOR_SIMPLE 0
#define MATERIAL_COLOR_UV 1
#define MATERIAL_COLOR_CUBE 2

#define MATERIAL_ENV_NONE 0
#define MATERIAL_ENV_REFLECT 1
#define MATERIAL_ENV_REFRACT 2
#define MATERIAL_ENV_REFLECT_REFRACT 3

#define MATERIAL_DEFAULT 0

#define FONT_ARIAL_32 0

#endif